--- !ditz.rubyforge.org,2008-03-06/project 
name: ditz-str
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: ditz-str
- !ditz.rubyforge.org,2008-03-06/component 
  name: WEBrick interface
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: Version 0.1
  status: :unreleased
  release_time: 
  log_events: 
  - - 2011-11-10 04:53:42.249739 Z
    - Nils Sandell <nils.sandell@systemstechnologyresearch.com>
    - created
    - Should include basic WEBrick server functionality.
